# coding: utf-8

"""
    Process Registry API

    Register processes with the Process Registry API.

    OpenAPI spec version: 0.1.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
    
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    
        http://www.apache.org/licenses/LICENSE-2.0
    
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class ProcessDefPatch(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        ProcessDefPatch - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'name': 'str',
            'author': 'int',
            'argv': 'str',
            'output_type': 'str',
            'output_parameters': 'str'
        }

        self.attribute_map = {
            'name': 'name',
            'author': 'author',
            'argv': 'argv',
            'output_type': 'output_type',
            'output_parameters': 'output_parameters'
        }

        self._name = None
        self._author = None
        self._argv = None
        self._output_type = None
        self._output_parameters = None

    @property
    def name(self):
        """
        Gets the name of this ProcessDefPatch.
        Name given to the process

        :return: The name of this ProcessDefPatch.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this ProcessDefPatch.
        Name given to the process

        :param name: The name of this ProcessDefPatch.
        :type: str
        """
        
        self._name = name

    @property
    def author(self):
        """
        Gets the author of this ProcessDefPatch.
        Unique ID of the user who created the process

        :return: The author of this ProcessDefPatch.
        :rtype: int
        """
        return self._author

    @author.setter
    def author(self, author):
        """
        Sets the author of this ProcessDefPatch.
        Unique ID of the user who created the process

        :param author: The author of this ProcessDefPatch.
        :type: int
        """
        
        self._author = author

    @property
    def argv(self):
        """
        Gets the argv of this ProcessDefPatch.
        JSON-formatted array being a list of arguments to give to the executable (can contain parameters)

        :return: The argv of this ProcessDefPatch.
        :rtype: str
        """
        return self._argv

    @argv.setter
    def argv(self, argv):
        """
        Sets the argv of this ProcessDefPatch.
        JSON-formatted array being a list of arguments to give to the executable (can contain parameters)

        :param argv: The argv of this ProcessDefPatch.
        :type: str
        """
        
        self._argv = argv

    @property
    def output_type(self):
        """
        Gets the output_type of this ProcessDefPatch.
        type of output (e.g. file, stream)

        :return: The output_type of this ProcessDefPatch.
        :rtype: str
        """
        return self._output_type

    @output_type.setter
    def output_type(self, output_type):
        """
        Sets the output_type of this ProcessDefPatch.
        type of output (e.g. file, stream)

        :param output_type: The output_type of this ProcessDefPatch.
        :type: str
        """
        
        self._output_type = output_type

    @property
    def output_parameters(self):
        """
        Gets the output_parameters of this ProcessDefPatch.
        JSON-formatted dictionary containing parameters regarding the output (depending on the output type)

        :return: The output_parameters of this ProcessDefPatch.
        :rtype: str
        """
        return self._output_parameters

    @output_parameters.setter
    def output_parameters(self, output_parameters):
        """
        Sets the output_parameters of this ProcessDefPatch.
        JSON-formatted dictionary containing parameters regarding the output (depending on the output type)

        :param output_parameters: The output_parameters of this ProcessDefPatch.
        :type: str
        """
        
        self._output_parameters = output_parameters

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

