sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "nightly"

matrix:
  fast_finish: true
  allow_failures:
  - python: "3.5"
  - python: "3.6"
  - python: "nightly"

before_install:
  - pip install --requirement dev-requirements.txt

script:
  - invoke test --coverage --verbose

after_success:
  - codecov
