sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "nightly"

matrix:
  fast_finish: true
  allow_failures:
  - python: "3.6"
  - python: "nightly"

before_install:
  - pip install --requirement dev-requirements.txt
  - invoke build

script:
  - invoke test --coverage

after_success:
  - codecov
